// Verified static data backbone (fixtures, venues, odds, WC pedigree, marquee career WC goals).
// This renders instantly and never depends on the network; the live API enriches it.

export const T = {
  MEX:{n:"Mexico",f:"🇲🇽",cf:"CONCACAF",titles:0,best:"QF ×2 (1970, 1986)",odds:"+100",
    players:[{nm:"Guillermo Ochoa",pos:"GK",club:"AEL Limassol",note:"Set for a record-equalling 6th World Cup in goal."},
             {nm:"Raúl Jiménez",pos:"FW",club:"Fulham",note:"Leads the line for the hosts of the opening match at the Azteca."}]},
  RSA:{n:"South Africa",f:"🇿🇦",cf:"CAF",titles:0,best:"Group stage (incl. hosts 2010)",odds:"+1400",
    players:[{nm:"Lyle Foster",pos:"FW",club:"Burnley",note:"Bafana's main Premier League goal threat."}]},
  KOR:{n:"Korea Republic",f:"🇰🇷",cf:"AFC",titles:0,best:"4th place (2002)",odds:"+290",
    players:[{nm:"Son Heung-min",pos:"FW",club:"LAFC",wc:{2018:1,2022:0},note:"Captain and talisman; scored the stunner vs Germany in 2018."},
             {nm:"Lee Kang-in",pos:"MF",club:"Paris Saint-Germain",note:"Creative hub of this Korea side."}]},
  CZE:{n:"Czechia",f:"🇨🇿",cf:"UEFA",titles:0,best:"R16 (2006); Czechoslovakia were finalists 1934 & '62",odds:"+260",
    players:[{nm:"Patrik Schick",pos:"FW",club:"Bayer Leverkusen",note:"Prolific finisher when fit."}]},

  CAN:{n:"Canada",f:"🇨🇦",cf:"CONCACAF",titles:0,best:"Group stage (1986, 2022)",odds:"+260",
    players:[{nm:"Alphonso Davies",pos:"DF",club:"Real Madrid",note:"World-class left side; co-host energy behind him in Toronto."},
             {nm:"Jonathan David",pos:"FW",club:"Juventus",note:"Canada's record scorer and penalty threat."}]},
  BIH:{n:"Bosnia & Herzegovina",f:"🇧🇦",cf:"UEFA",titles:0,best:"Group stage (2014)",odds:"+270",
    players:[{nm:"Edin Džeko",pos:"FW",club:"Fiorentina",wc:{2014:0},note:"Veteran captain, still the focal point in attack."}]},
  QAT:{n:"Qatar",f:"🇶🇦",cf:"AFC",titles:0,best:"Group stage (hosts 2022)",odds:"+3500",
    players:[{nm:"Akram Afif",pos:"FW",club:"Al-Sadd",note:"Two-time Asian Cup player of the tournament."}]},
  SUI:{n:"Switzerland",f:"🇨🇭",cf:"UEFA",titles:0,best:"QF (1934/38/54); R16 in 2014, '18, '22",odds:"-110",
    players:[{nm:"Granit Xhaka",pos:"MF",club:"Sunderland",note:"Midfield metronome and captain."},
             {nm:"Nico Elvedi",pos:"DF",club:"Borussia M'gladbach",note:"Anchors a typically stubborn Swiss back line."}]},

  BRA:{n:"Brazil",f:"🇧🇷",cf:"CONMEBOL",titles:5,best:"Champions ×5 (1958 to 2002)",odds:"-290",
    players:[{nm:"Vinícius Júnior",pos:"FW",club:"Real Madrid",wc:{2022:1},note:"Player-of-tournament candidate; sets the left side alight."},
             {nm:"Neymar",pos:"FW",club:"Santos",wc:{2014:4,2018:2,2022:1},note:"Back at 34 for a likely final World Cup; Brazil's all-time top scorer."},
             {nm:"Raphinha",pos:"FW",club:"Barcelona",wc:{2022:0},note:"Electric Barça campaign; carries set-piece and goal threat."}]},
  MAR:{n:"Morocco",f:"🇲🇦",cf:"CAF",titles:0,best:"4th place (2022), first African semifinalist",odds:"+450",
    players:[{nm:"Achraf Hakimi",pos:"DF",club:"Paris Saint-Germain",wc:{2022:0},note:"Best attacking full-back at the tournament; huge fantasy ceiling."},
             {nm:"Youssef En-Nesyri",pos:"FW",club:"Fenerbahçe",wc:{2022:2},note:"Headed the goal that knocked out Portugal in 2022."},
             {nm:"Brahim Díaz",pos:"MF",club:"Real Madrid",note:"Switched allegiance to Morocco; their creative spark."}]},
  HAI:{n:"Haiti",f:"🇭🇹",cf:"CONCACAF",titles:0,best:"Group stage (1974)",odds:"+10000",
    players:[{nm:"Frantzdy Pierrot",pos:"FW",club:"Gaziantep",note:"Target man leading a spirited Haiti attack."}]},
  SCO:{n:"Scotland",f:"🏴󠁧󠁢󠁳󠁣󠁴󠁿",cf:"UEFA",titles:0,best:"Group stage, first WC since 1998",odds:"+700",
    players:[{nm:"Scott McTominay",pos:"MF",club:"Napoli",note:"Serie A winner and Scotland's box-to-box goal source."},
             {nm:"Che Adams",pos:"FW",club:"Torino",note:"Leads the line in Scotland's most attacking spot vs Haiti."}]},

  USA:{n:"United States",f:"🇺🇸",cf:"CONCACAF",titles:0,best:"3rd place (1930)",odds:"-150",
    players:[{nm:"Christian Pulisic",pos:"FW",club:"AC Milan",wc:{2022:1},note:"Captain America; hosts' creator-in-chief."},
             {nm:"Weston McKennie",pos:"MF",club:"Juventus",note:"Engine of the midfield."}]},
  PAR:{n:"Paraguay",f:"🇵🇾",cf:"CONMEBOL",titles:0,best:"QF (2010)",odds:"+360",
    players:[{nm:"Miguel Almirón",pos:"FW",club:"Atlanta United",note:"Pace and directness on the break."}]},
  AUS:{n:"Australia",f:"🇦🇺",cf:"AFC",titles:0,best:"R16 (2006, 2022)",odds:"+450",
    players:[{nm:"Martin Boyle",pos:"FW",club:"Hibernian",note:"Socceroos' livewire forward."}]},
  TUR:{n:"Türkiye",f:"🇹🇷",cf:"UEFA",titles:0,best:"3rd place (2002)",odds:"+260",
    players:[{nm:"Arda Güler",pos:"MF",club:"Real Madrid",note:"The jewel of a rising Turkey side; set-piece and shooting threat."},
             {nm:"Kenan Yıldız",pos:"FW",club:"Juventus",note:"Breakout forward adding to Turkey's attack."}]},

  GER:{n:"Germany",f:"🇩🇪",cf:"UEFA",titles:4,best:"Champions ×4 (1954 to 2014)",odds:"-220",
    players:[{nm:"Joshua Kimmich",pos:"DF",club:"Bayern Munich",wc:{2018:0,2022:0},note:"Captain; plays right-back/midfield with elite set-piece delivery."},
             {nm:"Florian Wirtz",pos:"MF",club:"Liverpool",note:"Germany's creative future, now."},
             {nm:"Jamal Musiala",pos:"MF",club:"Bayern Munich",note:"Dribbling threat through the middle."}]},
  CUW:{n:"Curaçao",f:"🇨🇼",cf:"CONCACAF",titles:0,best:"World Cup debut, smallest nation ever to qualify",odds:"+4500",debut:true,
    players:[{nm:"Tahith Chong",pos:"MF",club:"Sheffield United",note:"Most recognisable name in a historic debutant squad."}]},
  CIV:{n:"Ivory Coast",f:"🇨🇮",cf:"CAF",titles:0,best:"Group stage",odds:"+600",
    players:[{nm:"Simon Adingra",pos:"FW",club:"Sunderland",note:"Pace on the flank for the Elephants."}]},
  ECU:{n:"Ecuador",f:"🇪🇨",cf:"CONMEBOL",titles:0,best:"R16 (2006)",odds:"+380",
    players:[{nm:"Enner Valencia",pos:"FW",club:"Internacional",wc:{2014:3,2022:3},note:"Ecuador's all-time WC scorer; every Ecuador goal in 2014 & 2022 was his."},
             {nm:"Moisés Caicedo",pos:"MF",club:"Chelsea",note:"World-class ball-winner anchoring midfield."}]},

  NED:{n:"Netherlands",f:"🇳🇱",cf:"UEFA",titles:0,best:"Runners-up ×3 (1974, '78, 2010)",odds:"-140",
    players:[{nm:"Cody Gakpo",pos:"FW",club:"Liverpool",wc:{2022:3},note:"Scored in all three group games in 2022; primary goal source."},
             {nm:"Denzel Dumfries",pos:"DF",club:"Inter Milan",wc:{2022:0},note:"Wing-back with real attacking output."},
             {nm:"Virgil van Dijk",pos:"DF",club:"Liverpool",note:"Captain and defensive cornerstone."}]},
  JPN:{n:"Japan",f:"🇯🇵",cf:"AFC",titles:0,best:"R16 ×4 (incl. beating Germany & Spain in 2022)",odds:"+340",
    players:[{nm:"Takefusa Kubo",pos:"FW",club:"Real Sociedad",note:"Creative leader, but Japan are without the injured Kaoru Mitoma."},
             {nm:"Wataru Endo",pos:"MF",club:"Liverpool",note:"Captain and midfield shield."}]},
  SWE:{n:"Sweden",f:"🇸🇪",cf:"UEFA",titles:0,best:"Runners-up (1958); 3rd in 1950 & 1994",odds:"+430",
    players:[{nm:"Alexander Isak",pos:"FW",club:"Liverpool",wc:{2022:0},note:"Elite finisher leading the line."},
             {nm:"Viktor Gyökeres",pos:"FW",club:"Arsenal",note:"Ruthless scorer; gives Sweden a fearsome front pair."}]},
  TUN:{n:"Tunisia",f:"🇹🇳",cf:"CAF",titles:0,best:"Group stage (beat France in 2022)",odds:"+1000",
    players:[{nm:"Hannibal Mejbri",pos:"MF",club:"Burnley",note:"Combative midfielder and emotional leader."}]},

  BEL:{n:"Belgium",f:"🇧🇪",cf:"UEFA",titles:0,best:"3rd place (2018), 'golden generation'",odds:"-220",
    players:[{nm:"Jérémy Doku",pos:"FW",club:"Manchester City",wc:{2022:0},note:"In-form dribbler; Belgium's most dangerous wide threat."},
             {nm:"Kevin De Bruyne",pos:"MF",club:"Napoli",wc:{2014:1,2018:1},note:"Still the creative axis when fit."}]},
  EGY:{n:"Egypt",f:"🇪🇬",cf:"CAF",titles:0,best:"Group stage",odds:"+390",
    players:[{nm:"Mohamed Salah",pos:"FW",club:"Liverpool",wc:{2018:2},note:"Talisman; carries Egypt's hopes almost single-handedly."}]},
  IRN:{n:"Iran",f:"🇮🇷",cf:"AFC",titles:0,best:"Group stage",odds:"+700",
    players:[{nm:"Mehdi Taremi",pos:"FW",club:"Inter Milan",wc:{2022:2},note:"Scored twice vs England in 2022; Iran's main man."}]},
  NZL:{n:"New Zealand",f:"🇳🇿",cf:"OFC",titles:0,best:"Group stage (unbeaten in 2010)",odds:"+1900",
    players:[{nm:"Chris Wood",pos:"FW",club:"Nottingham Forest",note:"Premier League goals lead the All Whites."}]},

  ESP:{n:"Spain",f:"🇪🇸",cf:"UEFA",titles:1,best:"Champions (2010) · Euro 2024 winners",odds:"-450",
    players:[{nm:"Lamine Yamal",pos:"FW",club:"Barcelona",note:"18-year-old superstar at his first World Cup (minor fitness watch for the opener).",debutStar:true},
             {nm:"Mikel Oyarzabal",pos:"FW",club:"Real Sociedad",wc:{2022:0},note:"Scored the Euro 2024 final winner; expected to start through the middle."},
             {nm:"Pedri",pos:"MF",club:"Barcelona",note:"Midfield conductor of the favourites."}]},
  CPV:{n:"Cape Verde",f:"🇨🇻",cf:"CAF",titles:0,best:"World Cup debut",odds:"+5000",debut:true,
    players:[{nm:"Ryan Mendes",pos:"FW",club:"Unattached",note:"Veteran captain of the Blue Sharks' historic first World Cup."}]},
  KSA:{n:"Saudi Arabia",f:"🇸🇦",cf:"AFC",titles:0,best:"R16 (1994); famously beat Argentina in 2022",odds:"+2200",
    players:[{nm:"Salem Al-Dawsari",pos:"FW",club:"Al-Hilal",wc:{2022:1},note:"Scored the winner vs Argentina in 2022."}]},
  URU:{n:"Uruguay",f:"🇺🇾",cf:"CONMEBOL",titles:2,best:"Champions ×2 (1930, 1950); 4th in 2010",odds:"+500",
    players:[{nm:"Federico Valverde",pos:"MF",club:"Real Madrid",note:"All-action midfield engine, now the team's leader."},
             {nm:"Darwin Núñez",pos:"FW",club:"Al-Hilal",wc:{2022:0},note:"Pace and power up top."}]},

  FRA:{n:"France",f:"🇫🇷",cf:"UEFA",titles:2,best:"Champions ×2 (1998, 2018); runners-up 2022",odds:"-215",
    players:[{nm:"Kylian Mbappé",pos:"FW",club:"Real Madrid",wc:{2018:4,2022:8},note:"Golden Boot 2022; the tournament's headline act and most-owned fantasy pick."},
             {nm:"Ousmane Dembélé",pos:"FW",club:"Paris Saint-Germain",wc:{2018:0,2022:0},note:"Reigning Ballon d'Or winner; France's wide threat."},
             {nm:"Michael Olise",pos:"MF",club:"Bayern Munich",note:"Breakout creator at his first World Cup."}]},
  SEN:{n:"Senegal",f:"🇸🇳",cf:"CAF",titles:0,best:"QF (2002)",odds:"+800",
    players:[{nm:"Nicolas Jackson",pos:"FW",club:"Bayern Munich",note:"Leads the line for Africa's heavyweight."},
             {nm:"Pape Matar Sarr",pos:"MF",club:"Tottenham",note:"Energetic midfield driver."}]},
  IRQ:{n:"Iraq",f:"🇮🇶",cf:"AFC",titles:0,best:"Group stage",odds:"+5000",
    players:[{nm:"Aymen Hussein",pos:"FW",club:"Al-Qadsiah",note:"Iraq's main striker; the Lions of Mesopotamia defend deep and well."}]},
  NOR:{n:"Norway",f:"🇳🇴",cf:"UEFA",titles:0,best:"R16 (1998), first WC since then",odds:"+275",
    players:[{nm:"Erling Haaland",pos:"FW",club:"Manchester City",note:"World Cup debutant after 16 goals in qualifying; pure goal machine.",debutStar:true},
             {nm:"Martin Ødegaard",pos:"MF",club:"Arsenal",note:"Captain and creative fulcrum on his WC debut."}]},

  ARG:{n:"Argentina",f:"🇦🇷",cf:"CONMEBOL",titles:3,best:"Champions ×3 (1978, '86, 2022)",odds:"-250",
    players:[{nm:"Lionel Messi",pos:"FW",club:"Inter Miami",wc:{2006:1,2014:4,2018:1,2022:7},note:"At 38, a record 6th World Cup; defending champions' captain."},
             {nm:"Julián Álvarez",pos:"FW",club:"Atlético Madrid",wc:{2022:4},note:"Scored four en route to the 2022 title; in superb club form."},
             {nm:"Lautaro Martínez",pos:"FW",club:"Inter Milan",wc:{2022:0},note:"Prolific for Inter; fights for the central striker role."}]},
  ALG:{n:"Algeria",f:"🇩🇿",cf:"CAF",titles:0,best:"R16 (2014)",odds:"+800",
    players:[{nm:"Riyad Mahrez",pos:"FW",club:"Al-Ahli",note:"Captain and matchwinner from the right."},
             {nm:"Mohamed Amoura",pos:"FW",club:"Wolfsburg",note:"Pace and goals leading the line."}]},
  AUT:{n:"Austria",f:"🇦🇹",cf:"UEFA",titles:0,best:"3rd place (1954), first WC since 1998",odds:"+370",
    players:[{nm:"David Alaba",pos:"DF",club:"Real Madrid",note:"Veteran leader of Austria's first World Cup in 28 years."},
             {nm:"Marcel Sabitzer",pos:"MF",club:"Borussia Dortmund",note:"Goals from midfield."}]},
  JOR:{n:"Jordan",f:"🇯🇴",cf:"AFC",titles:0,best:"World Cup debut, 2023 Asian Cup runners-up",odds:"+5000",debut:true,
    players:[{nm:"Mousa Al-Taamari",pos:"FW",club:"Montpellier",note:"Star man of Jordan's historic first World Cup."}]},

  POR:{n:"Portugal",f:"🇵🇹",cf:"UEFA",titles:0,best:"3rd place (1966); 4th in 2006",odds:"-215",
    players:[{nm:"Cristiano Ronaldo",pos:"FW",club:"Al-Nassr",wc:{2006:1,2010:1,2014:1,2018:4,2022:1},note:"At 41, a record 6th World Cup; first man to score at five."},
             {nm:"Bruno Fernandes",pos:"MF",club:"Manchester United",wc:{2022:2},note:"Penalties and creativity from the centre, central to everything."},
             {nm:"Nuno Mendes",pos:"DF",club:"Paris Saint-Germain",note:"Attacking left-back with clean-sheet and assist upside."}]},
  COD:{n:"DR Congo",f:"🇨🇩",cf:"CAF",titles:0,best:"As Zaire, group stage (1974)",odds:"+1400",
    players:[{nm:"Cédric Bakambu",pos:"FW",club:"Real Betis",note:"Experienced striker leading the Leopards' return after 52 years."}]},
  UZB:{n:"Uzbekistan",f:"🇺🇿",cf:"AFC",titles:0,best:"World Cup debut",odds:"+3500",debut:true,
    players:[{nm:"Eldor Shomurodov",pos:"FW",club:"Roma",note:"Talisman of Uzbekistan's first-ever World Cup."}]},
  COL:{n:"Colombia",f:"🇨🇴",cf:"CONMEBOL",titles:0,best:"QF (2014); R16 (2018)",odds:"+240",
    players:[{nm:"James Rodríguez",pos:"MF",club:"León",wc:{2014:6,2018:0},note:"Won the 2014 Golden Boot; still Colombia's captain and creator."},
             {nm:"Luis Díaz",pos:"FW",club:"Bayern Munich",note:"In-form winger on his World Cup debut."}]},

  ENG:{n:"England",f:"🏴󠁧󠁢󠁥󠁮󠁧󠁿",cf:"UEFA",titles:1,best:"Champions (1966); 4th in 2018",odds:"-280",
    players:[{nm:"Harry Kane",pos:"FW",club:"Bayern Munich",wc:{2018:6,2022:2},note:"2018 Golden Boot; England's all-time scorer and penalty taker."},
             {nm:"Jude Bellingham",pos:"MF",club:"Real Madrid",wc:{2022:0},note:"World-class midfield driver entering his prime."},
             {nm:"Bukayo Saka",pos:"FW",club:"Arsenal",wc:{2022:0},note:"Right-wing goal and assist threat."}]},
  CRO:{n:"Croatia",f:"🇭🇷",cf:"UEFA",titles:0,best:"Runners-up (2018); 3rd in 1998 & 2022",odds:"+340",
    players:[{nm:"Luka Modrić",pos:"MF",club:"AC Milan",wc:{2014:1,2018:2,2022:1},note:"2018 Golden Ball; orchestrates everything at 40."},
             {nm:"Joško Gvardiol",pos:"DF",club:"Manchester City",note:"Elite defender who also threatens going forward."}]},
  GHA:{n:"Ghana",f:"🇬🇭",cf:"CAF",titles:0,best:"QF (2010), minutes from a semifinal",odds:"+1100",
    players:[{nm:"Mohammed Kudus",pos:"MF",club:"Tottenham",note:"Ghana's standout creator and goal threat."}]},
  PAN:{n:"Panama",f:"🇵🇦",cf:"CONCACAF",titles:0,best:"Group stage (2018 debut)",odds:"+4000",
    players:[{nm:"Adalberto Carrasquilla",pos:"MF",club:"Houston Dynamo",note:"Midfield heartbeat of Los Canaleros."}]},
};

export const M = [
 {d:"Thu Jun 11",ds:"Thursday, June 11",t:"3:00",z:"PM ET",grp:"A",h:"MEX",a:"RSA",v:"Estadio Azteca",c:"Mexico City",fav:"h",conf:"lean",
  why:"Mexico open the whole tournament at a fortress where they rarely lose, and are clear Group A favourites (+100). South Africa will sit deep and counter.",
  take:{
    standfirst:"The whole tournament kicks off right here, and it's a trap dressed up as a gimme. Mexico have everything to lose at the Azteca; South Africa arrive with nothing to fear and a plan that has already embarrassed better sides than this.",
    sections:[
      {h:"How Mexico set up: Aguirre's control game",p:"Javier Aguirre is back for a third cycle and he is no romantic. Expect a 4-3-3 that slides into a 4-2-3-1 out of possession, built on control rather than chaos: Edson Álvarez shielding the back four, full-backs joining only when the picture is safe, and Mexico monopolising the ball, and 60%-plus possession is the baseline. Aguirre wants El Tri to win the game without ever being countered, so the tempo will be patient, almost deliberate, shifting the ball side to side until Lozano's pace or a Luis Chávez set-piece prises a gap open. The danger is obvious: against a deep, disciplined block, that patience can curdle into sterile possession, and opening-night nerves at the Azteca are very real."},
      {h:"How South Africa hurt them: Broos's counter-trap",p:"Hugo Broos won an AFCON with Cameroon and a bronze medal with this Bafana group by doing one thing superbly: defending as a unit and striking once. He will set up compact, two banks of four, inviting Mexico onto them and releasing Percy Tau and Lyle Foster into the channels the instant the ball turns over. Behind them, Ronwen Williams is one of the most underrated keepers at the tournament; he won a shootout almost single-handedly at AFCON 2024. Their great equaliser is the set piece; do not be surprised if their best chance of the night arrives from a corner."},
      {h:"The altitude myth nobody is checking",p:"Everyone repeats that the Azteca's 2,240m is Mexico's twelfth man. Against most opponents, true. Against South Africa, far less so. The South African league plays its football up on the Highveld, where Johannesburg sits above 1,700m, so these players live and train in thin air every week of their lives. The lung-busting edge Mexico usually enjoy is partly neutralised here, and Broos knows it. That single detail is the biggest reason I think this is tighter than the price suggests."},
      {h:"The players who decide it",p:"For Mexico it is the two ends of the spine: Edson Álvarez has to win the transition battle so they are never caught, and Raúl Jiménez has to take the half-chance a game like this hands you, because there will not be many. Keep Santiago Giménez in mind as the gambler off the bench if it is still goalless past the hour. For South Africa, Themba Zwane has the guile to spring the counter and Williams is the one who keeps them in it. The duel I will be watching most: Mexico's adventurous full-backs against Tau and Foster breaking in behind."},
      {h:"The X-factor: opening-night weight",p:"This is the very first match of a home World Cup, and that weight lands entirely on Mexico, a nation that expects, in a stadium that demands. Favourites in openers tend to tighten; underdogs play free. If South Africa get through the first 25 minutes still level, the anxiety in the stands starts to leak down onto the pitch."}
    ],
    verdict:"Mexico have the better players and they should win it. Jiménez or a set piece settles most versions of this game. But I am not buying a comfortable night. I will call it 1-0 or 2-1 Mexico with a nervy stretch in the middle, and a South Africa point would not shock me in the slightest. Lean Mexico, but hold the confidence loosely."
  }},
 {d:"Thu Jun 11",ds:"Thursday, June 11",t:"10:00",z:"PM ET",grp:"A",h:"KOR",a:"CZE",v:"Estadio Akron",c:"Guadalajara",fav:"x",conf:"toss",
  why:"A genuine coin-flip for second in the group: Czechia (+260) and Korea (+290) are priced almost level. Schick's finishing vs Son's threat decides it.",
  take:{
    standfirst:"For a neutral, this is the pick of the openers. Two sides who both genuinely fancy second place behind Mexico, separated by almost nothing in the market, and a perfect style clash: Korea's speed and craft against Czechia's muscle and set-piece menace.",
    sections:[
      {h:"How Korea play: Hong's quick, vertical game",p:"Hong Myung-bo, a 2002 World Cup semi-finalist as a player, has Korea pressing higher and playing far more vertically than they did under Klinsmann. The shape is a fluid 4-2-3-1 routed through two special talents: Lee Kang-in pulling the strings from the right half-space and Son Heung-min attacking the space in behind from the left. Win the ball back and Korea want to be in your box inside five seconds, with Hwang Hee-chan's diagonal runs stretching the back line. The insurance behind all of it is Kim Min-jae, a genuinely elite centre-back whose recovery pace lets the full-backs gamble forward."},
      {h:"How Czechia play: Hašek's direct, physical plan",p:"Czechia are everything Korea are not: bigger, more direct, and ruthless from dead balls. Ivan Hašek's side defend in a disciplined block, sit a fraction deeper, hunt the second balls, and feed Patrik Schick (when fit, one of the cleanest finishers in Europe) off the shoulder of the last defender. Their not-so-secret weapon is Tomáš Souček, a 6ft 4in midfielder who arrives late into the box and is worth a goal every few games from set pieces alone. If this turns scrappy and physical, that is precisely the game Czechia want to play."},
      {h:"The battle that settles it: Korea's high line vs Schick",p:"Here is the chess match. Korea want to squeeze the game high and play on the front foot, but a high line against Schick's diagonal runs is playing with fire, and Kim Min-jae will have to be close to flawless on the cover. At the other end, Korea's pace in transition terrifies a Czech back four that is not quick. Whoever wins that single exchange, Korea's press against Czechia's direct outlet, most likely wins the match."},
      {h:"Set pieces could be the whole story",p:"In a tight game between evenly-matched teams, the dead ball is the tie-breaker, and that lever points Czech. Souček and Schick give them two real aerial threats and a clear plan B that Korea simply do not carry to the same degree. Korea have to be ruthless and switched-on with their marking; one lapse of concentration from a corner could decide the group's closest opener."},
      {h:"Players to watch",p:"Lee Kang-in is the most important footballer on the pitch; if Korea are going to unpick a disciplined Czech block, his imagination is the key that turns the lock. Son Heung-min is still the finisher and the leader they look to in the big moment. For Czechia it is simpler: keep Schick fit and Souček dangerous, and let Lukáš Provod's left foot supply the wide deliveries that matter most."}
    ],
    verdict:"I genuinely cannot separate them, and the odds agree: this is the truest coin-flip on Matchday 1. Korea's individual ceiling (Son, Lee Kang-in, Kim Min-jae) is a shade higher, so if you forced a pick I would lean a 1-1 that Korea might nick late. But Czechia's set-piece threat makes a 1-0 either way just as live. I will call it a draw and a genuine tactical treat. Toss-up, and I mean it."
  }},

 {d:"Fri Jun 12",ds:"Friday, June 12",t:"3:00",z:"PM ET",grp:"B",h:"CAN",a:"BIH",v:"BMO Field",c:"Toronto",fav:"h",conf:"lean",
  why:"Co-hosts Canada have home advantage and the game's best player in Davies, but Džeko's Bosnia are dangerous, a narrow home lean."},
 {d:"Fri Jun 12",ds:"Friday, June 12",t:"9:00",z:"PM ET",grp:"D",h:"USA",a:"PAR",v:"SoFi Stadium",c:"Inglewood, CA",fav:"h",conf:"lean",
  why:"The hosts are favourites to win Group D and open at home, but Paraguay are organised and physical. Pulisic is the difference-maker."},

 {d:"Sat Jun 13",ds:"Saturday, June 13",t:"3:00",z:"PM ET",grp:"B",h:"QAT",a:"SUI",v:"Levi's Stadium",c:"Santa Clara, CA",fav:"a",conf:"high",
  why:"Switzerland are Group B favourites (-110) and far stronger top to bottom than Qatar. Expect Swiss control."},
 {d:"Sat Jun 13",ds:"Saturday, June 13",t:"6:00",z:"PM ET",grp:"C",h:"BRA",a:"MAR",v:"MetLife Stadium",c:"East Rutherford, NJ",fav:"h",conf:"lean",
  why:"The pick of MD1. Brazil are heavy group favourites (-290) but Morocco are the 2022 semifinalists with Hakimi and a brilliant block, the toughest 'big team' opener on the board."},
 {d:"Sat Jun 13",ds:"Saturday, June 13",t:"9:00",z:"PM ET",grp:"C",h:"HAI",a:"SCO",v:"Gillette Stadium",c:"Foxborough, MA",fav:"a",conf:"high",
  why:"Scotland's one clearly winnable group game. More quality and experience than debutant-level Haiti, and a soft spot for McTominay to score."},

 {d:"Sun Jun 14",ds:"Sunday, June 14",t:"12:00",z:"AM ET",grp:"D",h:"AUS",a:"TUR",v:"BC Place",c:"Vancouver",fav:"a",conf:"lean",
  why:"Türkiye's rising side, with Güler and Yıldız, carry more quality, but Australia are well-drilled and stubborn. Lean Türkiye."},
 {d:"Sun Jun 14",ds:"Sunday, June 14",t:"1:00",z:"PM ET",grp:"E",h:"GER",a:"CUW",v:"NRG Stadium",c:"Houston",fav:"h",conf:"high",
  why:"As lopsided as it gets: four-time champions Germany vs the smallest nation ever to qualify. A clean sheet and multi-goal Germany win is the expectation."},
 {d:"Sun Jun 14",ds:"Sunday, June 14",t:"4:00",z:"PM ET",grp:"F",h:"NED",a:"JPN",v:"AT&T Stadium",c:"Arlington, TX",fav:"h",conf:"lean",
  why:"Netherlands are group favourites (-140) but Japan beat Germany and Spain in 2022 and press hard, and the Dutch defence has wobbled. Closer than the badge suggests."},
 {d:"Sun Jun 14",ds:"Sunday, June 14",t:"7:00",z:"PM ET",grp:"E",h:"CIV",a:"ECU",v:"Lincoln Financial Field",c:"Philadelphia",fav:"a",conf:"toss",
  why:"Tight battle for the runner-up spot behind Germany. Ecuador's Caicedo-anchored balance edges the toss-up over Ivory Coast."},
 {d:"Sun Jun 14",ds:"Sunday, June 14",t:"10:00",z:"PM ET",grp:"F",h:"SWE",a:"TUN",v:"Estadio BBVA",c:"Monterrey",fav:"h",conf:"lean",
  why:"Sweden's Isak and Gyökeres front line is the most potent thing in this fixture; Tunisia defend well but lack the firepower to match it."},

 {d:"Mon Jun 15",ds:"Monday, June 15",t:"12:00",z:"PM ET",grp:"H",h:"ESP",a:"CPV",v:"Mercedes-Benz Stadium",c:"Atlanta",fav:"h",conf:"high",
  why:"The single safest result of MD1. Tournament favourites Spain (-450 to win the group) against a World Cup debutant, with a multi-goal win expected and the prime captaincy spot."},
 {d:"Mon Jun 15",ds:"Monday, June 15",t:"3:00",z:"PM ET",grp:"G",h:"BEL",a:"EGY",v:"Lumen Field",c:"Seattle",fav:"h",conf:"high",
  why:"Belgium are strong Group G favourites and far deeper than Egypt, who lean heavily on Salah. Belgian quality should tell."},
 {d:"Mon Jun 15",ds:"Monday, June 15",t:"6:00",z:"PM ET",grp:"H",h:"KSA",a:"URU",v:"Hard Rock Stadium",c:"Miami",fav:"a",conf:"high",
  why:"Uruguay are second favourites in the group (+500) with Valverde driving a serious side. Saudi Arabia can frustrate, but quality points one way."},
 {d:"Mon Jun 15",ds:"Monday, June 15",t:"9:00",z:"PM ET",grp:"G",h:"IRN",a:"NZL",v:"SoFi Stadium",c:"Inglewood, CA",fav:"h",conf:"lean",
  why:"Iran are seasoned tournament operators with Taremi up top; New Zealand will compete but Iran are the rightful favourites for the points."},

 {d:"Tue Jun 16",ds:"Tuesday, June 16",t:"12:00",z:"AM ET",grp:"J",h:"AUT",a:"JOR",v:"Levi's Stadium",c:"Santa Clara, CA",fav:"h",conf:"high",
  why:"Austria's first World Cup since 1998 starts against debutants Jordan. The European side's quality and experience make them clear favourites."},
 {d:"Tue Jun 16",ds:"Tuesday, June 16",t:"3:00",z:"PM ET",grp:"I",h:"FRA",a:"SEN",v:"MetLife Stadium",c:"East Rutherford, NJ",fav:"h",conf:"lean",
  why:"France (-215 in the group) have the firepower, but Senegal are Africa's heavyweight and a genuinely tough opener. Quality favours France without it being comfortable."},
 {d:"Tue Jun 16",ds:"Tuesday, June 16",t:"6:00",z:"PM ET",grp:"I",h:"IRQ",a:"NOR",v:"Gillette Stadium",c:"Foxborough, MA",fav:"a",conf:"high",
  why:"Haaland's long-awaited World Cup bow. Norway are group second-favourites (+275); Iraq defend deep, so chances may be at a premium, but the Norwegians should win."},
 {d:"Tue Jun 16",ds:"Tuesday, June 16",t:"9:00",z:"PM ET",grp:"J",h:"ARG",a:"ALG",v:"Arrowhead Stadium",c:"Kansas City",fav:"h",conf:"high",
  why:"Defending champions and a Messi farewell tour. Argentina are around -500 to win this match; Algeria have flair but the gap in quality is large."},

 {d:"Wed Jun 17",ds:"Wednesday, June 17",t:"1:00",z:"PM ET",grp:"K",h:"POR",a:"COD",v:"NRG Stadium",c:"Houston",fav:"h",conf:"high",
  why:"Portugal (-215 in the group) against a DR Congo side back at the World Cup after 52 years. Ronaldo, Bruno and Co. should have far too much."},
 {d:"Wed Jun 17",ds:"Wednesday, June 17",t:"4:00",z:"PM ET",grp:"L",h:"ENG",a:"CRO",v:"AT&T Stadium",c:"Arlington, TX",fav:"h",conf:"lean",
  why:"A heavyweight opener. England are favourites (-280 in the group) but Croatia, the 2018 finalists still marshalled by Modrić, are the toughest team they'll face before the latter stages."},
 {d:"Wed Jun 17",ds:"Wednesday, June 17",t:"7:00",z:"PM ET",grp:"L",h:"GHA",a:"PAN",v:"BMO Field",c:"Toronto",fav:"h",conf:"lean",
  why:"Ghana carry more pedigree and Kudus's quality; Panama are organised and won't be steamrolled, but the Black Stars are favoured."},
 {d:"Wed Jun 17",ds:"Wednesday, June 17",t:"10:00",z:"PM ET",grp:"K",h:"UZB",a:"COL",v:"Estadio Azteca",c:"Mexico City",fav:"a",conf:"high",
  why:"Colombia are a top-tier side with James and Luis Díaz; Uzbekistan are admirable debutants but the South Americans should control this comfortably."},
];
